"""Canonical NS (GHBSN) station-epoch table — generated from the SOTA list, consumed by stations.py.

22 of the 220 GHBSN stations were physically RELOCATED during operation (12 m – 5.2 km; N108 and
N166 twice), so one station code can mean two or three different positions depending on date. The
pipeline treats each epoch as its OWN station:

  * a moved station is suffixed from its FIRST epoch: ``N010a`` (2017-01-01..2022-10-13),
    ``N010b`` (2022-10-14..); a plain code (``N001``) always means "never moved" (user convention,
    2026-08-04). Lowercase suffixes, matching the GHBSN convention.
  * waveforms/picks always carry the BASE code (the archive is stored per base code and detection
    is position-free); the epoch code enters at the association boundary and is the only identity
    downstream (station tables, .phs, station.dat, SAC filenames + headers).

Source of truth: ``config.NS_STATION_CSV`` = data/metadata/stations/ns/20240715/
GHBSN_info_ver202312_modified.csv — the user's double-checked SOTA table. Validated 2026-08-04
against every other available source; where they disagree the SOTA table wins:
  * the original ver202312 list and the 240220 suffixed list carry a 4-station block shift
    (N088/N089/N176/N177, 8.8–13.5 km) that the SOTA table fixed (confirmed by the dataless SEED);
  * the 240220 suffixed list additionally pastes N018's coordinates into N019 (12.9 km error);
  * the dataless SEED (2020-06 delivery) is stale past ~Oct 2019 (misses later moves) and has a
    one-digit longitude typo at N115 (129.05096 for 129.06096 — three list sources agree on .06096);
  * five stations differ from the dataless by 20–66 m (survey-refinement scale) — SOTA accepted.

``build()`` regenerates data/metadata/stations/derived/ns_epochs_canonical.csv (tracked in git);
``load()`` reads it, rebuilding on demand if missing or older than the SOTA source.
"""
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config

CANONICAL = os.path.join(config.STATION_TABLE_CACHE, "ns_epochs_canonical.csv")

_HEADER = """\
# Canonical NS (GHBSN) station-epoch table — GENERATED by ufpipe.ns_epochs; do not hand-edit.
# Source (SOTA): data/metadata/stations/ns/20240715/GHBSN_info_ver202312_modified.csv
# Convention: moved stations carry lowercase epoch suffixes from their FIRST epoch (N010a, N010b);
#             a plain code means the station never moved. `datadir` = base code = waveform dir name.
# Validation 2026-08-04: SOTA beats all other sources (original+240220 lists: 4-station block shift
#             + N019=N018 paste; dataless SEED: stale past Oct 2019 + N115 longitude typo).
"""


def build(out=CANONICAL):
    """Regenerate the canonical epoch table from the SOTA list. Returns the DataFrame."""
    d = pd.read_csv(config.NS_STATION_CSV)
    d.columns = [c.strip().lower() for c in d.columns]
    d["t0"] = pd.to_datetime(d.starttime)
    d["t1"] = pd.to_datetime(d.endtime)
    # normalise to BASE codes regardless of source style (the SOTA list repeats the base code per
    # epoch; older lists carried lowercase suffixes already) — suffixes are re-derived below.
    d["station"] = d.station.str.replace(r"[a-z]$", "", regex=True)
    d = d.dropna(subset=["stla", "stlo"]).sort_values(["station", "t0"]).reset_index(drop=True)
    rows = []
    for base, g in d.groupby("station", sort=True):
        g = g.sort_values("t0").reset_index(drop=True)
        multi = len(g) > 1
        for k, r in g.iterrows():
            code = f"{base}{chr(ord('a') + k)}" if multi else base
            # HALF-OPEN epochs: an epoch runs up to the NEXT epoch's start, not to its own listed
            # end date. The source list stores `endtime` as a bare DATE (2020-02-19 = midnight), so
            # taking it literally leaves the whole move day in a gap between epochs — picks there
            # match no epoch, keep the base code, and get discarded (2020: 238 N103 + 110 N160
            # picks lost exactly this way). Consumers test t0 <= t < t1.
            t1 = g.t0[k + 1] if k + 1 < len(g) else r.t1
            rows.append(dict(net="NS", sta=code, datadir=base, lat=r.stla, lon=r.stlo,
                             elev=r.stel, t0=r.t0, t1=t1, band=str(r.channel).strip()))
    out_df = pd.DataFrame(rows)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as fh:
        fh.write(_HEADER)
        out_df.to_csv(fh, index=False)
    return out_df


def load():
    """The canonical epoch table (rebuilds if missing or older than the SOTA source)."""
    if (not os.path.exists(CANONICAL)
            or os.path.getmtime(CANONICAL) < os.path.getmtime(config.NS_STATION_CSV)):
        return build()
    return pd.read_csv(CANONICAL, comment="#", parse_dates=["t0", "t1"])


def epoch_code(base, when, table=None):
    """Epoch code in force for `base` at time `when` (plain code if the station never moved;
    returns `base` unchanged when nothing matches, so callers degrade gracefully)."""
    t = table if table is not None else load()
    g = t[t.datadir == base]
    if len(g) <= 1:
        return base
    w = pd.Timestamp(when)
    hit = g[(g.t0 <= w) & (w <= g.t1)]
    return hit.iloc[0].sta if len(hit) else base


if __name__ == "__main__":
    df = build()
    mv = df[df.sta != df.datadir]
    print(f"canonical NS epochs: {len(df)} rows, {df.datadir.nunique()} stations, "
          f"{mv.datadir.nunique()} moved (suffixed) -> {CANONICAL}")
